= Board Support Package
:toc:

:sectnums:

== CSR

=== Functions

These functions concern the CSR:

`uint64_t csr_get_cycle(void)`

* Get the current cycle count since last reset as a 64-bit unsigned number.

`uint64_t csr_get_instret(void)`

* Get the number of retired instructions since last reset as a 64-bit unsigned number.

`uint64_t csr_get_time(void)`

* Get the number of microseconds since last reset as a 64-bit unsigned number.

`uint64_t csr_get_mhpmcounter3(void)` +
`uint64_t csr_get_mhpmcounter4(void)` +
`uint64_t csr_get_mhpmcounter5(void)` +
`uint64_t csr_get_mhpmcounter6(void)` +
`uint64_t csr_get_mhpmcounter7(void)` +
`uint64_t csr_get_mhpmcounter8(void)` +
`uint64_t csr_get_mhpmcounter9(void)`

* Get the number of counter events since last reset as a 64-bit unsigned number. Note: Zihpm extenion must be enabled in the hardware.

=== Macros

These macros concern the CSR:

`csr_read(csr)`

* Returns the 32-bit unsigned contents of a CSR register.

`csr_write(csr, val)`

* Writes the unsigned 32-bits value in `val` to the given CSR register.

`csr_set(csr, val)`

* Set bits in named CSR register

`csr_clear(csr, val)`

* Clear bits in named CSR register

`csr_swap(csr, val)`

* Reads the named CSR (the return value) and places `val` in the named CSR.


== GPIO

=== Functions

`uint32_t gpioa_readpin(uint32_t pin)`

* Get the state of an input pin. Please use one pin at a time. The result is either `GPIO_PIN_RESET` or `GPIO_PIN_SET`.


`void gpioa_writepin(uint32_t pin, uint32_t value)`

* Set the state of an output pin. More than one pin may be set in one call. The state is either `GPIO_PIN_RESET` or `GPIO_PIN_SET`.

`void gpioa_togglepin(uint32_t pin)`

* Toggle the state of a output pin. More than one pin may be toggled in one call.

Note: `pin` is a pin list. Each bit in the 32-bit `pin` represents one pin with the same index number.

=== Macros

`GPIO_PIN_SET` +
`GPIO_PIN_RESET`

* The values for setting and resetting pins.

`GPIO_PIN_0` +
`GPIO_PIN_1` +
`GPIO_PIN_2` +
`GPIO_PIN_3` +
`GPIO_PIN_4` +
`GPIO_PIN_5` +
`GPIO_PIN_6` +
`GPIO_PIN_7` +
`GPIO_PIN_8` +
`GPIO_PIN_9` +
`GPIO_PIN_10` +
`GPIO_PIN_11` +
`GPIO_PIN_12` +
`GPIO_PIN_13` +
`GPIO_PIN_14` +
`GPIO_PIN_15` +
`GPIO_PIN_16` +
`GPIO_PIN_17` +
`GPIO_PIN_18` +
`GPIO_PIN_19` +
`GPIO_PIN_20` +
`GPIO_PIN_21` +
`GPIO_PIN_22` +
`GPIO_PIN_23` +
`GPIO_PIN_24` +
`GPIO_PIN_25` +
`GPIO_PIN_26` +
`GPIO_PIN_27` +
`GPIO_PIN_28` +
`GPIO_PIN_29` +
`GPIO_PIN_30` +
`GPIO_PIN_31` +
`PIO_PIN_ALL`

* These macros define pins in a pin list. The macros may be OR-ed to make a pin list.

`GPIO_EXTC_EDGE_RISING` +
`GPIO_EXTC_EDGE_FALLING` +
`GPIO_EXTC_EDGE_BOTH`

* Selecting the edge(s) for the external input pin interrupt

`gpioa_set_extc(pinnr, edge)`

* Select pin `pinnr` with edge(s) `edge`. `pinnr` is a 5-bit number between 0 and 31.


== I2C

=== Functions

`void i2c1_init(uint32_t val)` +
`void i2c2_init(uint32_t val)`

* Initialize the I2C1/I2C2 peripherals. `val` is copied one-to-one to the CTRL register.

`uint8_t i2c1_receive_byte(void)` +
`uint8_t i2c2_receive_byte(void)`

* Receive one byte from the I2C1/I2C2 peripherals.

`uint32_t i2c1_receive(uint8_t address, uint8_t *buf, uint32_t len)` +
`uint32_t i2c2_receive(uint8_t address, uint8_t *buf, uint32_t len)`

* Receive `len` bytes from target with address `address` and store the bytes in the buffer pointed by `buf`. A return value of 0 indicates success. Includes START and STOP conditions.

`uint32_t i2c1_transmit_address(uint8_t address)` +
`uint32_t i2c2_transmit_address(uint8_t address)`

* Transmit an address on the I2C bus, including a START condition. A return value of 0 indicates success (target acknowledged).

`uint32_t i2c1_transmit_address_only(uint8_t address)` +
`uint32_t i2c2_transmit_address_only(uint8_t address)`

* Transmit an addess on the  I2C bus, including START and STOP conditions. Can be used to detect targets. A return value of 0 indicates success (target acknowledged).

`uint32_t i2c1_transmit_byte(uint8_t data)` +
`uint32_t i2c2_transmit_byte(uint8_t data)`

* Transmit one byte on the I2C1/I2C2 peripherals. A return value of 0 indicates success (target acknowledged). 

`int32_t i2c1_transmit(uint8_t address, uint8_t *buf, uint32_t len)` +
`int32_t i2c2_transmit(uint8_t address, uint8_t *buf, uint32_t len)`

* Transmit a buffer pointed by `buf` with length `len` to the target with address `address`, including START and STOP conditions.

=== Macros

`I2C_PRESCALER_FM(A)` +
`I2C_PRESCALER_SM(A)` +

* When used to set CTRL, these macros calculate the (shifted) precaler value for system frequecy `A`.

`I2C_FAST_MODE` +

* When used to set CTRL, this macro selects Fast Mode.

`I2C_STANDARD_MODE` +

* When used to set CTRL, this macro selects Standard Mode.

`I2C_TCIE` +

* When used to set CTRL, this macro set transmit complete interrupt enable.

`I2C_MACK` +

* When used to set CTRL, this macro sets Master Acknowledge.

`I2C_HARDSTOP` +

* When used to set CTRL, this macro generates a STOP condition on the bus *without* any transmission.

`I2C_START` +

* When used to set CTRL, this macro generates a START condition on bus on the next transmission.

`I2C_STOP` +

* When used to set CTRL, this macro generates a STOP condition on bus on the next transmission.

`I2C_BUSY` +

* When used when reading STAT, this macro indicated that the bus is busy.

`I2C_AF` +

* When used when reading STAT, this macro filters the Acknowledge Failed bit.

`I2C_TC` +

* When used when reading STAT, this macro filters the Transmission Complete bit.

`I2C_TRANS` +

* When used when reading STAT, this macro indicates that the device is transmitting.

`I2C_READ` +

* Used to indicate read, when transmitting the address.

`I2C_WRITE`

* Used to indicate write, when transmitting the address.

== SPI

=== Functions

`void spi1_init(uint32_t value)` +
`void spi2_init(uint32_t value)`

* Initialize the SPI device. `value` is copied one-to-one to the CTRL register.

`void spi1_receive(uint8_t *buf, uint32_t len, uint32_t dummy)` +
`void spi2_receive(uint8_t *buf, uint32_t len, uint32_t dummy)`

* Receive `len` bytes of data and store them in a buffer pointed by `buf`, while sending bytes with value `dummy`.

`void spi1_transmit(uint8_t *buf, uint32_t len)` +
`void spi2_transmit(uint8_t *buf, uint32_t len)`

* Transmit `len` bytes of data pointed by `buf`, ignore received data.

`void spi1_transmit_receive(uint8_t *buft, uint8_t *bufr, uint32_t len)` +
`void spi2_transmit_receive(uint8_t *buft, uint8_t *bufr, uint32_t len)`

* Transmit and receive `len` bytes of data, `buft` for transmitting and `bufr` for receiving.

`uint32_t spi1_transfer(uint32_t data)` +
`uint32_t spi2_transfer(uint32_t data)`

* Transmit a datum `data`, which may be any supported size and return the received datum.

`__attribute__((weak)) void spi1_csenable(void)` +
`__attribute__((weak)) void spi2_csenable(void)`


* Weak placeholders for activating the Chip Select signals. The user must override these functions with own functions. These weak functions do nothing.

`__attribute__((weak)) void spi1_csdisable(void)` +
`__attribute__((weak)) void spi2_csdisable(void)`

* Weak placeholders for disabling the Chip Select signals. The user must override these functions with own functions. These weak functions do nothing.

=== Macros

`SPI_MODE0` +
`SPI_MODE1` +
`SPI_MODE2` +
`SPI_MODE3`

* When used to set CTRL, this macro selects the clocking mode.

`SPI_SIZE8` +
`SPI_SIZE16` +
`SPI_SIZE24` +
`SPI_SIZE32`

* When used to set CTRL, this macro selects the transmission size.

`SPI_PRESCALER0` +
`SPI_PRESCALER1` +
`SPI_PRESCALER2` +
`SPI_PRESCALER3` +
`SPI_PRESCALER4` +
`SPI_PRESCALER5` +
`SPI_PRESCALER6` +
`SPI_PRESCALER7`

* When used to set CTRL, these macros select the prescaler (2^{_number_ + 1}^)

`SPI_TCIE`

* When used to set CTRL, this macro enables interrupt generation.

`SPI_TC`

* When reading STAT, this macro filters the tranmission complete bit.


== TIMER1

=== Functions


`void inline timer1_enable(void)`

* Enable TIMER1.

`void inline timer1_disable(void)`

* Disable TIMER1.

`uint32_t inline timer1_getcounter(void)`

* Get the current TIMER1 counter value as a unsigned 32-bit number.

`void inline timer1_setcounter(uint32_t cntr)`

* Set the TIMER1 counter value to the unsigned 32-bit number `cntr`.

`void inline timer1_setcompare(uint32_t cmpt)`

* Set TIMER1 compare T register (CMPT) to the unsigned 32-bit number `cmpt`.

`void inline timer1_enable_interrupt(void)`

* Enable TIMER1 interrupt.

`void inline timer1_disable_interrupt(void)`

* Disable TIMER1 interrupt.

`void inline timer1_clear_interrupt(void)`

* Clear TIMER1 overflow flags, this clears a pending interrupt.

=== Macros

`TIMER1_EN`

* When setting CTRL, this macro enables the timer.

`TIMER1_TCIE`

* When setting CTRL, this macro selects Interrupt Enable.

`TIMER1_TC`

* When reading STAT, this macro indicates Timer Complete (overflow)

== UART

`void uart1_init(uint32_t baudrate, uint32_t ctrl)`

* Initialize UART1. `baudrate` is the baud rate in bits per second. `ctrl` is copied to the CTRL register.

`void uart1_putc(int ch)`

* Write one character via UART1.

`void uart1_puts(char *s)`

* Write a null-terminated string via UART1.

`int uart1_getc(void)`

* Read one character via UART1.

`int uart1_gets(char buffer[], int size)`

* Read at most `size` minus 1 characters from UART1 into `buffer`, and null-terminate buffer. Returns the number of characters received. Simple line-editing is supported: backspace and delete are supported. Return/enter terminates reading characters. Return/enter is not part of the returned buffer.

`int uart1_printf(const char *format, ...)`

* Print formatted string via UART1, at most 255 characters. Parameters are the same as `printf`. Returns the number of printed characters. Note: to print floating point numbers, supply the linker with `-u _printf_float`. Note: `long long` integers (a.k.a 64-bit) are not supported due to lack of the `nano` library.

`void uart1_printlonglong(int64_t v)`

* Print a signed long long integer (a.k.a. `int64_t`) via UART1.

`void uart1_printulonglong(uint64_t v)`

* Print an unsigned long long integer (a.k.a. `uint64_t`) via UART1.

`int uart1_hasreceived(void)`

* Returns != 0 if a character has been received via UART1.


== Watchdog (WDT)

=== Functions

`void wdt_init(uint32_t val)`

* Initialize the watchdog. `val` is copied to the CTRL register.

`void wdt_reset(void)`

* Reset the watchdog.

`void wdt_start(void)`

* Start the watchdog.

`void wdt_stop(void)`

* Stop the watchdog.

=== Macros

'WDT_EN`

* When writing CTRL, this macro enables counting of the watchdog.

'WDT_NMI`

* When writing CTRL, this macro selects generating an NMI when the watchdog times out. If not set, a watchog timeout triggers a system wide reset.

'WDT_LOCK`

* When writing CTRL, this macro inhibits further manipulation of the watchdog. If this bit is set in CTRL, any further writes to CTRL triggers an NMI or a system wide reset.

'WDT_PRESCALER(A)`

* This macro calculates the (shifted) watchdog counter reset value.

'WDT_PASSWORD`

* This macro expand to the watchdog password.


More to be added.

